[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364

# Issue: Everything here will not work if there are no cards on screen to calculate with
[[patches]] #This being a separate file felt warranted
[patches.pattern]
target = "functions/common_events.lua"
pattern = "-- TARGET: evaluate your own general effects"
position = "before"
match_indent = true
payload = '''
if card.ability.numbertaker_rankless and card.base.nominal > 0 then card.base.nominal = 1 end
if context.ending_booster and G.GAME.all_in_jest.dizzard_shop and G.shop.alignment.offset.y ~= -5.3 then
    G.E_MANAGER:add_event(Event({
        trigger = 'after',
        func = function()
            if G.shop.alignment.offset.y ~= -5.3 then
                G.shop.alignment.offset.y = -5.3
            end
            return true
        end
    }))
end
if context.end_of_round then
    G.GAME.all_in_jest.dizzard_shop = false
end
if context.setting_blind then
    if G.GAME.aij_show_hand then
        G.hand.states.visible = true
        G.GAME.aij_show_hand = nil
    end
    for k, v in pairs(G.jokers.cards) do
        if v.ability and v.ability.all_in_jest and v.ability.all_in_jest.has_been_rerolled then
            card_eval_status_text(v, "extra", nil, nil, nil, {message = localize("k_reset"), colour = G.C.FILTER})
            All_in_Jest.reroll_joker(v, v.ability.all_in_jest.has_been_rerolled, 'stage_production')
            v.ability.all_in_jest.has_been_rerolled = nil
        end
    end
end
if context.cardarea == G.play and context.all_in_jest and context.all_in_jest.main_scoring_chip_vaules and not context.repetition then
    ret.playing_card = {}
    local chips = card:get_chip_bonus()
    if chips ~= 0 then
        ret.playing_card.chips = chips
    end
end
-- Perma stuff for Jokers
if context.joker_main then
    ret.perma_joker_triggers = {}
    local chips = (card.ability.perma_bonus or 0)
    if chips ~= 0 then
        ret.perma_joker_triggers.chips = chips
    end
    
    local mult = (card.ability.perma_mult or 0)
    if mult ~= 0 then
        ret.perma_joker_triggers.mult = mult
    end
    
    local x_mult = (card.ability.perma_x_mult or 0)
    if x_mult > 0 then
        ret.perma_joker_triggers.x_mult = x_mult + 1
    end
    
    local p_dollars = (card.ability.perma_p_dollars or 0)
    if p_dollars ~= 0 then
        ret.perma_joker_triggers.p_dollars = p_dollars
    end
    
    local x_chips = (card.ability.perma_x_chips or 0)
    if x_chips > 0 then
        ret.perma_joker_triggers.x_chips = x_chips + 1
    end
end
if card.aij_seal_edition and card.seal then
    ret.aij_seal_edition = {}
    local old_edition = card.edition and copy_table(card.edition)
    card.edition = card.aij_seal_edition
    context.calculate_seal_edition = true
    local edition = card:calculate_edition(context)
    context.calculate_seal_edition = nil
    if edition then
        ret.aij_seal_edition = edition
    end
    card.edition = old_edition
end
if context.aij_inherent_enhancement or context.aij_other_enhancement then return ret end
if card.aij_inherent_effects then
    local i = 0
    local j = 0
    for k, v in pairs(card.aij_inherent_effects) do
        i = i + 1
        for _k, _v in pairs(card.aij_inherent_effects[k]) do
            j = j + 1
            if not _v.aij_setting_ability then
                if k == 'editions' then
                    local old_edition = card.edition and copy_table(card.edition)
                    card.edition = _v
                    local edition = card:calculate_edition(context)
                    if edition then
                        ret['aij_inherent_effects'..j..i] = edition
                    end
                    card.edition = old_edition
                end
            end
        end
    end
end
-- if not card.ability.aij_other_center or not card.ability.aij_other_center['ability'] then
--     card.ability.aij_other_center = card.ability.aij_other_center or {}
--     card.ability.aij_other_center['ability'] = card.config.aij_other_center and card.config.aij_other_center['ability']
-- end
'''

[[patches]] #For repetition on cards
[patches.pattern]
target = "functions/common_events.lua"
pattern = "-- TARGET: evaluate your own repetition effects"
position = "before"
match_indent = true
payload = '''
if context.aij_inherent_enhancement or context.aij_other_enhancement then return ret end
'''

# [[patches]] #For debuffed joker cards
# [patches.pattern]
# target = "functions/common_events.lua"
# pattern = "if not card:can_calculate(context.ignore_debuff, context.remove_playing_cards*"
# position = "before"
# match_indent = true
# payload = '''
# if (context.joker_main or context.initial_scoring_step or context.main_eval) and not context.aij_ran_away_new_before then
#     if next(SMODS.find_card("j_aij_run")) and card.ability.set == "Joker" then
#         local index, run_index = 0, 0
#         local runs = SMODS.find_card("j_aij_run")
#         local run_index = runs[#runs].rank
#         local cur_index = card.rank
#         if cur_index < run_index then
#             local new_context = {joker_main = context.joker_main}

#             if context.joker_main and not context.initial_scoring_step then
#                 context.joker_main = nil
#                 context.aij_ran_away = true
#             end
#             if context.initial_scoring_step and context.main_eval and not context.aij_ran_away_new_before then
#                 context.aij_ran_away_before = true
#                 context.aij_ran_away_new_before = true
#                 for k, v in pairs(context) do 
#                     if k ~= 'joker_main' then
#                         new_context[k] = v
#                     end
#                 end
#                 SMODS.calculate_context(new_context) -- Allows initial_scoring_step to still be called
#                 context.joker_main = true
#                 context.initial_scoring_step = nil
#                 context.aij_ran_away_new_before = nil
#             end
#         end
#     end
# end
# if context.joker_main and next(SMODS.find_card("j_aij_greasepaint")) and not context.blueprint then
#     for k, v in pairs(SMODS.find_card("j_aij_greasepaint")) do
#         if card.debuff then
#             SMODS.calculate_effect({xmult = v.ability.extra.xmult}, card)
#         end
#     end
# end
# '''

# [[patches]]
# [patches.pattern]
# target = "functions/common_events.lua"
# pattern = "return ret, post_trig"
# position = "before"
# match_indent = true
# payload = '''
# if next(SMODS.find_card("j_aij_run")) and card.config.center_key ~= 'j_aij_run' and card.ability.set == "Joker" then
#     local index, cur_index, run_index = 0, 0, 0
#     for k, v in pairs(G.jokers.cards) do
#         index = index + 1
#         if v.config.center_key == 'j_aij_run' then
#             run_index = index
#         end
#         if v == card then
#             cur_index = index
#         end
#     end
#     if cur_index < run_index then
#         if context.aij_ran_away_before then
#             context.initial_scoring_step = true
#             context.joker_main = nil
#             context.aij_ran_away_before = nil
#         end
#         if context.aij_ran_away then
#             context.joker_main = true
#             context.aij_ran_away = nil
#         end
#     end
# end
# '''



# [[patches]] #For debuffed played cards
# [patches.pattern]
# target = '=[SMODS _ "src/utils.lua"]'
# pattern = "--if card is debuffed"
# position = "after"
# match_indent = true
# payload = '''
# if scoring_hand and card.debuff then
#     if in_scoring and next(SMODS.find_card("j_aij_greasepaint")) then
#         for k, v in pairs(SMODS.find_card("j_aij_greasepaint")) do
#             if card.debuff then
#                 SMODS.calculate_effect({xmult = v.ability.extra.xmult}, card)
#             end
#         end
#     end
# end
# '''
